### ISSUE TITLE
Add DEFAULT COMMAND information to help page (CMD or ENDPOINT)

### ISSUE THREAD

**Issue by chrisnegus** [ashcrow/image-helpgen#4]
I'd like to see a section named something like "DEFAULT COMMAND" added to the resulting help.md file by image-helpgen. The section could say something like: "If no command is passed to this container at run time, the default command run is: $COMMAND" The value of $COMMAND could be taken from the CMD line (if no ENDPOINT entry exists). If there is an ENDPOINT, the ENDPOINT + CMD could be used.

**Comment by ashcrow** [comment]
This makes sense to me. I think it will be pretty easy as we are using the same parser that parses `Dockerfile`s and can probably live in our parse [loop](https://github.com/ashcrow/image-helpgen/blob/master/cmd/dockerfile.go#L47-L66).

**Comment by ashcrow** [comment]
```
<snip/>

# Default Command
/usr/bin/etcd-env.sh /usr/bin/etcd

<snip/>
```
