### ISSUE TITLE
Drop guided input

### ISSUE THREAD

**Issue by ashcrow** [ashcrow/image-helpgen#7]
I think the guided input should be removed. While there are some corner cases where someone may want to be asked questions to answer instead of documenting their Dockerfile I don't think it's worth dragging along. @chrisnegus  WDYT?

**Comment by ashcrow** [comment]
Got a +1 in person from Chris.

**Comment by ashcrow** [comment]
Merged

**Comment by chrisnegus** [comment]
As we said when we spoke in person, I agree this is a good idea. Best to put the effort into making the tool work great with Dockerfiles.
